---
- hosts: pi
  gather_facts: true
  become: true
  tasks:
  - name: update and upgrade system packages
    apt:
      upgrade: yes
      update_cache: yes

  roles:
    - mariadb
    - php
    - drupal
  