---
- name: install php prereqs
  apt: 
     name:
     - lsb-release 
     - apt-transport-https 
     - ca-certificates 

- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    id: 15058500A0235D97F5D10063B188E2B695BD4743
    state: present

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo

- name: Update apt caches after repo is added (Debian).
  apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
    - ansible_distribution == "Debian"



- name: install php7.4 with all modules
  package: name={{ item }} state=present
  with_items:
    - php7.4
    - php7.4-curl
    - php7.4-gd
    - php7.4-cli
    - php7.4-mysql
    - php7.4-xml
    - php7.4-mbstring
    - php7.4-fpm
    - php7.4-json
    - php7.4-intl
    - php7.4-zip
    - php7.4-filter
    - php7.4-zlib
    - php7.4-openssl
    - php7.4-mysqli
    - php7.4-pdo
    - php7.4-imagick
    - php7.4-curl
    - php7.4-exif

- name: start and enable service
  service: name=php7.4-fpm state=started enabled=yes

- name: setting timezone in php.ini
  lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: ^;date.timezone or ^date.timezone
    line: date.timezone = {{ date_timezone }}
    state: present

- name: setting timezone in php.ini
  lineinfile:
    path: /etc/php/7.4/fpm/php.ini
    regexp: ^memory_limit
    line: memory_limit = {{ memory_limit }}
    state: present

- name: restart php7.4-fpm
  service: name=php7.4-fpm state=restarted